# Generated by Django 2.1.7 on 2020-08-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotobat', models.FloatField(max_length=3)),
                ('dama', models.FloatField(max_length=3)),
                ('date', models.DateTimeField()),
                ('tozih', models.CharField(max_length=300)),
            ],
        ),
    ]
